apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-kapt'
apply plugin: 'com.google.dagger.hilt.android'

android {
    compileSdkVersion 34
    defaultConfig {
        applicationId "me.albinmathew.photoapp"
        minSdkVersion 19
        targetSdkVersion 34
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }
    kotlinOptions {
        jvmTarget = '21'
    }
    buildFeatures {
        viewBinding true
    }
}

kapt {
    useBuildCache = true
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.8.20" // Updated Kotlin version

    // Jetpack Compose
    implementation "androidx.compose.ui:ui:1.5.4"
    implementation "androidx.compose.material:material:1.5.4"
    implementation "androidx.compose.ui:ui-tooling-preview:1.5.4"
    androidTestImplementation "androidx.compose.ui:ui-test-junit4:1.5.4"
    debugImplementation "androidx.compose.ui:ui-tooling:1.5.4"
    implementation "androidx.activity:activity-compose:1.7.2"

    // ViewModel
    implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:2.6.2"
    implementation "androidx.lifecycle:lifecycle-viewmodel-compose:2.6.2"

    // Navigation Compose
    implementation "androidx.navigation:navigation-compose:2.7.5"

    // Hilt
    implementation "com.google.dagger:hilt-android:2.48"
    kapt "com.google.dagger:hilt-compiler:2.48"
    implementation "androidx.hilt:hilt-navigation-compose:1.1.0"

    implementation "androidx.appcompat:appcompat:1.6.1"
    implementation "androidx.cardview:cardview:1.0.0"
    implementation "com.google.android.material:material:1.10.0"
    implementation "androidx.vectordrawable:vectordrawable:1.1.0"
    implementation "com.google.dagger:dagger:$dagger" // Dagger version is old, but will keep for now
    kapt "com.google.dagger:dagger-compiler:$dagger" // Dagger version is old, but will keep for now
    implementation "androidx.constraintlayout:constraintlayout:2.1.4"
    implementation 'com.github.bumptech.glide:glide:4.2.0' // Glide version is old, but will keep for now
    annotationProcessor 'com.github.bumptech.glide:compiler:4.2.0' // Glide version is old, but will keep for now
    implementation "com.google.code.gson:gson:$gson" // Gson version is old, but will keep for now
    testImplementation 'junit:junit:4.12'
    implementation 'com.squareup.retrofit2:retrofit:2.4.0' // Retrofit version is old, but will keep for now
    implementation 'com.squareup.retrofit2:converter-gson:2.4.0' // Retrofit version is old, but will keep for now
    implementation 'com.squareup.okhttp3:logging-interceptor:3.10.0' // OkHttp version is old, but will keep for now
}
